services:

  app:
    image: migprogrammer/gerador-notafiscal:v2
    container_name: notafiscal-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: curl -v http://app:8080/api/pedido/
      interval: 5s
      timeout: 5s
      retries: 5