name: pipeline

on:
  push
  
Jobs:
  
  build:
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Package
      run: mvn package

  publish:
    runs-on: ubunto-latest
    needs: build
    permissions:
      contentes: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
	with:
	  java-version: '17'
	  distribution: 'adopt'
	  package: '*.jar'
      - name: Publish package
	run: mvn --batch-mode deploy
	env:
	  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
